#!/usr/bin/env bash
#
# Provision the backend: generate a token, build the topic list, deploy the
# edge function, create the private bucket.
#
# Safe to run again. It reuses the existing token rather than issuing a new one,
# so re-running does not orphan a device that is already configured.
#
# BASH 3.2 ONLY - macOS ships 3.2 and always will. No mapfile, no ${x,,}.
#
set -u

HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/.." && pwd)
CONF="$HOME/.desk-recorder"
TOKEN_FILE="$CONF/token"
TOPICS_FILE="${KNOB_TOPICS_FILE:-$ROOT/topics.txt}"
FN_SLUG="transcriber-ingest"
BUCKET="transcriber"

command -v supabase >/dev/null || {
  echo "The Supabase CLI is not installed."
  echo "  brew install supabase/tap/supabase"
  echo "or see https://supabase.com/docs/guides/cli"
  exit 1
}

# Installed but signed out is the more likely of the two, and on its own the CLI
# reports it as a deploy failure several steps further down, by which point a
# token has been generated and generated.ts written. Catch it first.
PROBE=$(supabase projects list --output json 2>/dev/null || true)
case "$PROBE" in
  \[*|\{*) ;;
  *)
    echo "The Supabase CLI is installed but not signed in to your account."
    echo "  supabase login"
    echo "Then run this again."
    exit 1 ;;
esac
unset PROBE

PROJECT_REF="${KNOB_PROJECT_REF:-}"
if [ -z "$PROJECT_REF" ]; then
  printf "Supabase project ref (the subdomain in your project URL): "
  read -r PROJECT_REF
fi
case "$PROJECT_REF" in
  [a-z]*) ;;
  *) echo "That does not look like a project ref."; exit 1 ;;
esac

mkdir -p "$CONF"
chmod 700 "$CONF"

# ---- the token -------------------------------------------------------------
# 256 bits of randomness. The server stores only its SHA-256, so this value
# exists in exactly two places: this file, and the device.
if [ ! -s "$TOKEN_FILE" ]; then
  openssl rand -hex 32 > "$TOKEN_FILE"
  chmod 600 "$TOKEN_FILE"
  echo "Generated a new device token."
else
  echo "Using the existing device token."
fi
# Hash the token VALUE, not the file: the file ends in a newline and hashing
# that gives a digest the device's bearer will never match. A 401 on every
# upload with everything else looking correct is this bug.
TOKEN_HASH=$(printf '%s' "$(cat "$TOKEN_FILE")" | shasum -a 256 | cut -d' ' -f1)

# ---- topics ----------------------------------------------------------------
[ -f "$TOPICS_FILE" ] || {
  echo "No topics file at $TOPICS_FILE"
  echo "Create one with a line per topic, e.g. Work / Personal / Book notes."
  exit 1
}

# slugify: lowercase, anything not a letter or digit becomes a dash, collapse
# and trim dashes. "Book.Club" -> "book-club". The server's own
# validator is ^[a-z0-9][a-z0-9-]{0,40}$ and this has to satisfy it.
slugify() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -e 's/[^a-z0-9]\{1,\}/-/g' -e 's/^-\{1,\}//' -e 's/-\{1,\}$//' \
    | cut -c1-41
}

GEN="$HERE/generated.ts"
{
  echo "// GENERATED by deploy.sh - do not edit, your changes will be overwritten."
  echo "// Topics come from topics.txt. The token hash comes from ~/.desk-recorder/token."
  echo ""
  echo "export const TOKEN_SHA256 = '$TOKEN_HASH';"
  echo ""
  echo "export const TOPICS: { slug: string; label: string; folder: string }[] = ["
} > "$GEN"

COUNT=0
SEEN=""   # bash 3.2 has no associative arrays, so a delimited string it is
while IFS= read -r line || [ -n "$line" ]; do
  # strip CR (a topics.txt edited on Windows), then trim
  line=$(printf '%s' "$line" | tr -d '\r' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
  case "$line" in ''|'#'*) continue ;; esac
  slug=$(slugify "$line")
  [ -n "$slug" ] || { echo "Skipping '$line': no usable characters for a slug."; continue; }
  # Two topics that reduce to the same slug would share one storage folder and
  # one transcript destination, which looks like recordings going missing.
  # Accents are the usual cause: "Cafe" and "Café" both become "caf".
  case "$SEEN" in
    *"|$slug|"*)
      echo "Two topics both become '$slug', and they would share a folder."
      echo "Rename one of them in $TOPICS_FILE, then run this again."
      exit 1 ;;
  esac
  SEEN="$SEEN|$slug|"
  # The label is what the screen shows. The folder is what your Mac creates, so
  # it is the label with the characters a filename cannot hold taken out: a
  # slash would make "Book notes / ideas" into two nested folders, and a colon
  # is still trouble on macOS. Everything else, including spaces and dots, is
  # kept so the folder reads like the topic rather than like a slug.
  folder=$(printf '%s' "$line" | sed -e 's#[/:]# #g' -e 's/  \{1,\}/ /g' -e 's/^ *//' -e 's/ *$//')
  esc_label=$(printf '%s' "$line"   | sed "s/'/\\\\'/g")
  esc_folder=$(printf '%s' "$folder" | sed "s/'/\\\\'/g")
  echo "  { slug: '$slug', label: '$esc_label', folder: '$esc_folder' }," >> "$GEN"
  COUNT=$((COUNT + 1))
done < "$TOPICS_FILE"

echo "];" >> "$GEN"

[ "$COUNT" -gt 0 ] || { echo "topics.txt has no usable lines."; exit 1; }
# The dial wraps around a fixed array on the device.
[ "$COUNT" -le 24 ] || { echo "$COUNT topics is more than the device's 24. Trim topics.txt."; exit 1; }
echo "Topics: $COUNT"

# ---- deploy ----------------------------------------------------------------
# The CLI only deploys from supabase/functions/<slug>/, so a workdir is staged.
STAGE=$(mktemp -d)
trap 'rm -rf "$STAGE"' EXIT
mkdir -p "$STAGE/supabase/functions/$FN_SLUG"
cp "$HERE/index.ts" "$GEN" "$STAGE/supabase/functions/$FN_SLUG/"

# --no-verify-jwt IS NOT OPTIONAL. The device authenticates with a bearer token
# whose SHA-256 this function checks itself; it has no Supabase JWT. Deploying
# without this flag turns JWT verification on and every upload starts 401ing.
echo "Deploying the function..."
supabase functions deploy "$FN_SLUG" \
  --project-ref "$PROJECT_REF" \
  --no-verify-jwt \
  --use-api \
  --workdir "$STAGE" || { echo "Deploy failed."; exit 1; }

# ---- the bucket ------------------------------------------------------------
# Private, always. These are recordings of your conversations.
echo "Checking the storage bucket..."
SRK=$(supabase projects api-keys --project-ref "$PROJECT_REF" --output json 2>/dev/null \
      | python3 -c 'import sys,json
try:
    ks=json.load(sys.stdin)
except Exception:
    sys.exit(0)
for k in ks:
    if k.get("name")=="service_role":
        print(k.get("api_key",""))
        break' 2>/dev/null)

if [ -z "$SRK" ]; then
  echo
  echo "Could not read the service key automatically, so the bucket has not been checked."
  echo "Create it by hand, once: Supabase dashboard > Storage > New bucket"
  echo "  name: $BUCKET     public: OFF"
else
  CODE=$(curl -s -o /dev/null -w '%{http_code}' \
    -X POST "https://$PROJECT_REF.supabase.co/storage/v1/bucket" \
    -H "apikey: $SRK" -H "Authorization: Bearer $SRK" \
    -H 'content-type: application/json' \
    -d "{\"name\":\"$BUCKET\",\"id\":\"$BUCKET\",\"public\":false}")
  case "$CODE" in
    200|201) echo "Bucket '$BUCKET' created, private." ;;
    *)
      # Everything else, including the ordinary case of the bucket already being
      # there. Storage answers a duplicate with HTTP 400 and puts "statusCode":
      # "409" INSIDE the body, so the HTTP code on its own cannot tell "already
      # yours" from "something broke". Guessing it wrong matters: re-running this
      # script is the documented way to change your topics, so a false alarm here
      # fires every single time anyone edits topics.txt. So ask the bucket.
      GOT=$(curl -s --max-time 30 \
        "https://$PROJECT_REF.supabase.co/storage/v1/bucket/$BUCKET" \
        -H "apikey: $SRK" -H "Authorization: Bearer $SRK")
      case "$GOT" in
        *"\"name\":\"$BUCKET\""*)
          case "$GOT" in
            *'"public":true'*)
              echo "Bucket '$BUCKET' exists but is PUBLIC, and these are recordings of"
              echo "your conversations. Make it private:"
              echo "  Supabase dashboard > Storage > $BUCKET > Settings, public OFF" ;;
            *) echo "Bucket '$BUCKET' already exists, private." ;;
          esac ;;
        *)
          echo "Bucket check returned HTTP $CODE. Create it by hand if uploads fail:"
          echo "  Supabase dashboard > Storage > New bucket, name $BUCKET, public OFF" ;;
      esac ;;
  esac
fi
unset SRK

# ---- prove it ----------------------------------------------------------------
# An endpoint that answers with the topic list is the only evidence worth having.
echo "Checking the function answers..."
GOT=$(curl -s --max-time 30 \
  -H "Authorization: Bearer $(cat "$TOKEN_FILE")" \
  "https://$PROJECT_REF.supabase.co/functions/v1/$FN_SLUG/categories")
case "$GOT" in
  *'"categories"'*) echo "Backend is live and answering with your topics." ;;
  '')  echo "No response from the function. It may still be starting - try again in a minute."; exit 1 ;;
  *)   echo "Unexpected response from the function:"; echo "  $(printf '%s' "$GOT" | cut -c1-200)"; exit 1 ;;
esac
