/*
 * ============================================================
 * KNOB TRANSCRIBER - INGEST + WORKER API
 * ============================================================
 * One function, two callers:
 *
 *   the DEVICE   POST /ingest      - upload a WAV chunk into a topic
 *                GET  /categories  - the dial's list, served not flashed
 *   your MAC     GET  /pending     - what needs transcribing
 *                GET  /file        - fetch one recording
 *                POST /done        - move it to processed/ after transcription
 *
 * AUTH BY TOKEN HASH. The bearer's SHA-256 must match the hash in
 * generated.ts. A hash is safe in a public repo - reversing 192 bits of
 * randomness is not a thing - and it means no secret ever has to be pasted
 * into a terminal. The token itself exists in exactly two places: the device
 * and your Mac's config file.
 *
 * generated.ts is written by deploy.sh from your token and your topics.txt.
 * You do not edit this file.
 *
 * STORAGE SHAPE. Private bucket `transcriber`:
 *   incoming/<topic>/<filename>.wav   uploaded, awaiting transcription
 *   processed/<topic>/<filename>.wav  transcribed, kept as the archive
 * Your Mac never holds a Supabase key. It lists and fetches through this
 * function with the same bearer the device uses. Storage calls inside use the
 * runtime's own SUPABASE_SERVICE_ROLE_KEY, which never leaves the function.
 */

import { TOKEN_SHA256, TOPICS } from './generated.ts';

const BUCKET = 'transcriber';

async function sha256hex(s: string): Promise<string> {
  const d = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(s));
  return [...new Uint8Array(d)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

const SB = Deno.env.get('SUPABASE_URL')!;
const KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
/*
 * BOTH HEADERS, MEASURED NOT ASSUMED. With only `Authorization: Bearer`,
 * storage answered "Invalid Compact JWS" - the runtime hands the function a
 * new-format secret key, not a legacy JWT, and storage reads those from
 * `apikey`. Sending both satisfies either key format.
 */
const auth = { apikey: KEY, Authorization: `Bearer ${KEY}` };

/* A path is <topic>/<name>.wav under a fixed prefix, and nothing in it gets to
 * traverse anywhere. Belt and braces on top of the bearer. */
const safe = (s: string) => /^[a-z0-9][a-z0-9-]{0,40}$/.test(s);
const safeFile = (s: string) => /^[A-Za-z0-9._-]{1,80}\.wav$/.test(s);

Deno.serve(async (req) => {
  const given = req.headers.get('authorization')?.replace(/^Bearer\s+/i, '') ?? '';
  if ((await sha256hex(given)) !== TOKEN_SHA256) {
    return new Response('unauthorized', { status: 401 });
  }

  const url = new URL(req.url);
  // Path arrives as /transcriber-ingest/<action>
  const action = url.pathname.split('/').filter(Boolean).pop() ?? '';

  if (req.method === 'GET' && action === 'categories') {
    // The worker sends ?scope=all. It gets the same list, and the parameter is
    // kept so the worker does not care which version of this function is
    // deployed.
    return Response.json({ categories: TOPICS });
  }

  if (req.method === 'POST' && action === 'ingest') {
    const category = url.searchParams.get('category') ?? '';
    const filename = url.searchParams.get('filename') ?? '';
    if (!TOPICS.some((c) => c.slug === category) || !safeFile(filename)) {
      return Response.json({ error: 'bad topic or filename' }, { status: 400 });
    }
    const body = await req.arrayBuffer();
    // A WAV header alone is 44 bytes; anything near that is a dud chunk and
    // storing it would just make the worker invoke whisper on nothing.
    if (body.byteLength < 1000) {
      return Response.json({ error: 'too small' }, { status: 400 });
    }
    const path = `incoming/${category}/${filename}`;
    const up = await fetch(`${SB}/storage/v1/object/${BUCKET}/${path}`, {
      method: 'POST',
      headers: { ...auth, 'content-type': 'audio/wav', 'x-upsert': 'true' },
      body,
    });
    if (!up.ok) {
      return Response.json(
        { error: `store ${up.status}: ${(await up.text()).slice(0, 200)}` },
        { status: 502 },
      );
    }
    /* The device treats this as confirmed only if `bytes` matches what it sent,
     * and deletes its local copy only then. Do not drop this field. */
    return Response.json({ ok: true, path, bytes: body.byteLength });
  }

  if (req.method === 'GET' && action === 'pending') {
    const out: { path: string; category: string; name: string; size: number }[] = [];
    for (const c of TOPICS) {
      const res = await fetch(`${SB}/storage/v1/object/list/${BUCKET}`, {
        method: 'POST',
        headers: { ...auth, 'content-type': 'application/json' },
        body: JSON.stringify({
          prefix: `incoming/${c.slug}`,
          limit: 100,
          sortBy: { column: 'name', order: 'asc' },
        }),
      });
      if (!res.ok) continue;
      for (const f of (await res.json()) ?? []) {
        if (f?.name?.endsWith('.wav')) {
          out.push({
            path: `incoming/${c.slug}/${f.name}`,
            category: c.slug,
            name: f.name,
            size: f?.metadata?.size ?? 0,
          });
        }
      }
    }
    return Response.json({ pending: out });
  }

  if (req.method === 'GET' && action === 'file') {
    const path = url.searchParams.get('path') ?? '';
    const [prefix, category, name] = path.split('/');
    // processed/ is readable too: the archive is the only copy once a chunk is
    // moved, and re-fetching it is how a transcript gets re-run with a better
    // model without asking the device for it again.
    if ((prefix !== 'incoming' && prefix !== 'processed') ||
        !safe(category ?? '') || !safeFile(name ?? '')) {
      return Response.json({ error: 'bad path' }, { status: 400 });
    }
    const res = await fetch(`${SB}/storage/v1/object/${BUCKET}/${path}`, {
      headers: auth,
    });
    if (!res.ok) return Response.json({ error: res.status }, { status: 404 });
    return new Response(res.body, { headers: { 'content-type': 'audio/wav' } });
  }

  if (req.method === 'POST' && action === 'done') {
    const path = url.searchParams.get('path') ?? '';
    const [prefix, category, name] = path.split('/');
    if (prefix !== 'incoming' || !safe(category ?? '') || !safeFile(name ?? '')) {
      return Response.json({ error: 'bad path' }, { status: 400 });
    }
    const res = await fetch(`${SB}/storage/v1/object/move`, {
      method: 'POST',
      headers: { ...auth, 'content-type': 'application/json' },
      body: JSON.stringify({
        bucketId: BUCKET,
        sourceKey: path,
        destinationKey: `processed/${category}/${name}`,
      }),
    });
    if (!res.ok) {
      return Response.json(
        { error: `move ${res.status}: ${(await res.text()).slice(0, 200)}` },
        { status: 502 },
      );
    }
    return Response.json({ ok: true });
  }

  return Response.json({ error: 'unknown action' }, { status: 404 });
});
